### ISSUE TITLE
'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:36:46

### ISSUE THREAD

**Issue by fbemm** [AndreaGuarracino/paf2chain#1]
Hi Andrea,

nice to see that there is a paf2chain converter. I tested it like this:

./build/paf2chain/target/release/paf2chain --input asm2asm.paf

PAF was generated with `minimap2` and `-x asm5 -c --cs=long`.

I got the following error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:36:46
stack backtrace:
   0:     0x55d54e876b70 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d54e876b70 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d54e876b70 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d54e876b70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d54e89235c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55d54e874aa5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55d54e878abb - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d54e878abb - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d54e878abb - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55d54e878591 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55d54e879184 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55d54e878c37 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x55d54e87706c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d54e878bc9 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55d54e80aab1 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55d54e80a9fd - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x55d54e80e54c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h4322a4877158179e
  17:     0x55d54e810492 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h821adc1be48c2508
  18:     0x55d54e812e7b - paf2chain::paf::PafFile::for_each_line_in_file::h8dc0f39f2e1b73f1
  19:     0x55d54e80e033 - paf2chain::main::h2534806b7b5a1f2e
  20:     0x55d54e80e103 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb08c24efb957a98c
  21:     0x55d54e80cc69 - std::rt::lang_start::{{closure}}::h5e7274398358ae3e
  22:     0x55d54e879689 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  23:     0x55d54e879689 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  24:     0x55d54e879689 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  25:     0x55d54e879689 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  26:     0x55d54e879689 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  27:     0x55d54e80e0d2 - main
  28:     0x7f3b23b68bf7 - __libc_start_main
  29:     0x55d54e80b221 - <unknown>
```

Somehow the unwind of the CIGAR string throws an error. Any idea where to start looking for the problem?

**Comment by AndreaGuarracino** [comment]
Hi @fbemm, thank you for using `paf2chain`.

I've fixed the error. I was not parsing the PAF lines optimally.

Let me know!

**Comment by fbemm** [comment]
Hi @AndreaGuarracino,

works like charm.

Thanks a lot!
